#!/usr/bin/env python3

import subprocess
import os, re, sys, time, string
import argparse

re_file_line_error= re.compile(r'.*:[0-9]*:.*')

re_warning = re.compile("(Package|Class)( (?P<pkg>.*)) Warning: (?P<text>.*)$")

re_package_error = re.compile(".*Package (?P<pkg>.*) Error: .*$")

class LatexCompileError(Exception): pass
class BibtexError(Exception): pass

def run_pdflatex():
    """Run pdflatex on jobname.
    In case of success, return silently.
    In case of error, pretty-print the error message and raise a LatexCompileError."""
        
    try:
        subprocess.check_output(["pdflatex",
                                 "-halt-on-error",
                                 "-file-line-error",
                                 "-synctex=1",
                                 "-shell-escape",
                                 "-interaction=nonstopmode",
                                 jobname],
                                stderr=subprocess.STDOUT,
        )
        return 
    except subprocess.CalledProcessError as e:
        log=e.output.decode('ascii',errors='replace').splitlines()
    
    acc=""
    prefix=None
    for line in log:

        # TeX breaks outputs at 79 characters. here we rejoin the fragments
        if len(line)==79:
            acc+=line
            continue
        elif acc:
            line=acc+line
            acc=""

        # long error logic. cf #14 #37
        if prefix is not None:
            if line[:len(prefix)] == prefix:
                text.append( line[len(prefix):].strip() )
            else:
                line=" ".join(text)
                break

        if "LaTeX Error:" in line: # cf #07
            break

        if re_package_error.match(line):
            m=re_package_error.match(line)
            prefix = "(%s)" % m.groupdict()["pkg"]
            text = [line]
            continue
            
        if re_file_line_error.search(line):
            break

    else:
        print("could not understand error ; dumping raw logfile")
        # try to be useful even if we could not understand the log
        print("...")
        print("...")
        print("\n".join( log[-10:] )) # cf #33

        raise LatexCompileError # notify caller of compile error

    # 1) display the (pretty-printed) main error message
    print(line)

    # 2) print the details, i.e. everything up to the offending line
    try:
        # first, we try locate the main error message, so as to start from there
        i=1+log.index(line[:79]) # :79 to unjoin line cf #37
    except ValueError:
        # Note: this happens for instance in test-cases #16, which I
        # don't want to write specific logic for. take that, fancyvrb.
        raise LatexCompileError #notify caller of compile error
    
    for detail in log[i:]:
        if detail.strip() in line:
            # discard this fragment if already joined into "line"
            continue
        if prefix is not None: # iff we are dealing with a package error
            # similarly: discard long-error fragments when already joined
            if detail[ len(prefix):].strip() in line:
                continue
            # and discard generic RTFM advice
            if detail == "See the "+prefix[1:-1]+" package documentation for explanation.":
                continue
        # supress superfluous noise: RTFM, boilerplate, etc.
        if detail.strip() in ["See the LaTeX manual or LaTeX Companion for explanation.",
                              "Type  H <return>  for immediate help.",
                              "Type X to quit or <RETURN> to proceed,",
                              "Enter file name:",
                              "...", "<read *>",
                              ""]:
            continue
        # suppress interactive querying for all extensions (.sty and others)
        if "or enter new name. (Default extension:" in detail:
            continue

        print(detail)

        # Have we reached the offending line yet ?
        if detail[:2].startswith("l."): 
            j=log.index(detail) # kludge
            if log[j+1].strip(): # offending line is sometimes displayed broken in two pieces cf #14
                print(log[j+1])
            break    
    
    raise LatexCompileError # notify caller of compile error

def bibtex_needed(old_aux,new_aux):
    log=open( jobname+".log" ).read()
    
    if "No file "+jobname+".bbl" in log:
        # print "bibtex is needed because no file "+jobname+".bbl"
        return True # test-cases #03, #15...
             
    if ( os.path.isfile(jobname+".bbl") and # test-case #15
        ("LaTeX Warning: Citation " in log)): # test-case #22
        # print "bibtex is needed because Citation undefined"
        return True

    # design note: we rerun bibtex even if there were only warnings,
    # so as to annoy the user, hoping for them to correct their .bib
    # files :-)
    if os.path.isfile(jobname+".blg"):
        blg=open( jobname+".blg" ).read()
        if "error message" in blg: return True # test-case #31
        if "Warning--" in blg: return True # test-case #32

    # detect hard-coded bibliographies (and maybe other corner cases)
    # which don't use bibtex at all. (cf e.g. #15)
    if not os.path.isfile(jobname+".bbl") and not os.path.isfile(jobname+".blg"):
        return False

    # on a fresh document, the aux file doesn't exist before the first pass
    if old_aux is None:
        old_aux=""
        
    old_aux = old_aux.decode('ascii')
    new_aux = new_aux.decode('ascii')
        
    old_citations = [ line[10:-1] for line in old_aux.splitlines() if line[:10] == r'\citation{' ]
    new_citations = [ line[10:-1] for line in new_aux.splitlines() if line[:10] == r'\citation{' ]

    # compare both sets to detect new or removed citations (cf #22 #40)
    if set(old_citations) != set(new_citations):
        # print "bibtex is needed because some citations have added or removed"
        return True

    if os.path.isfile(jobname+".blg"): # cf test-case #49
        last_bibtex_time = os.path.getmtime(jobname+".blg")
        bibnames=[ line[18:].strip() for line in open( jobname+".blg" ).readlines() if 'Database file' in line ]
        for bibname in bibnames: # iterate over all bibtex files, cf test-case #50
            if '-blx.bib' in bibname: continue # irrelevant because this one is biblatex-generated
            if os.path.getmtime(bibname) >= last_bibtex_time:
                return True

    return False

def run_bibtex():
        print("running BibTeX on %s..." % jobname)
    
        # design  note: I  decide to  abort  the build  process on  bibtex
        # errors, but to proceed on warnings
        #
        # and anyway, we remain silent if no errors nor warnings
    
        bibtex_output=None
        try:
            bibtex_output=subprocess.check_output(["bibtex",jobname]).decode('ascii')
        except subprocess.CalledProcessError as e:
            print("") # an empty line
            print(e.output.decode('ascii')[:-1])
            # Nirvana: pretty-print bibtex errors ?
            raise BibtexError
        
        if "Warning--" in bibtex_output:
            # just repeat what bibtex said.
            print(bibtex_output[:-1])
            # Nirvana: pretty-print bibtex warnings ?


#####################################################################
# Page and file tracking logic.
#
# keeps track of current document page and current source file so that
# warnings and errors are reported with relevant details

# GS-29/04/2014-16:07. remove the closing bracket. see test-cases.
# GS-22/05/2014-12:11. add the non-capturing-group matching end-of-string
re_page = re.compile("\[(?P<num>[0-9]+)(?:$|[^/0-9])")

class PageFileTracker():
    def __init__(self):
        self.current_pagenum=1
        self.update_currentfile_should_skip_line=False # XXX
        self.opened_files=[]
        self.print_all_filenames=False # Once we start printing filenames, we will print them all

        # guess maximum page number
        self.max_pagenum=0
        for line in open( jobname+".log" ):
            if "Output written on "+jobname+".pdf" in line:
                self.max_pagenum=int(line.split('(')[1].split()[0])
        
                
    def update_page (self,line):
        ms = re_page.findall(line)
        if ms:
            self.current_pagenum = max(self.current_pagenum, int(ms[-1]) + 1)


    def update_currentfile (self,line):
        """Parse the given logline and keep track of the file being processed"""

        # if line.count('(' ) + line.count(')'):
        #     print '##%d#%d##' % (line.count('('),
        #                          line.count(')') ) , line
        #     print "opened files:", tracker_opened_files

        if self.update_currentfile_should_skip_line:
            self.update_currentfile_should_skip_line=False
            return 

        # skip the (dangerous) line after a badbox warning, so as not to
        # be confused by text coming from the document (test-cases #35, #42)
        if line.startswith("Underfull") or line.startswith("Overfull"):
            self.update_currentfile_should_skip_line=True
            pass

        # we  walk the  logline one  character  at a  time, searching  for
        # parentheses,  and tracking  nesting level.  Some of  the opening
        # parentheses are  followed by a pathname,  so we push these  on a
        # pathname stack.
        while line:
            if line[0] is ')':
                try:
                    self.opened_files.pop()
                except: # this is a workaround for #51
                    pass

            if line[0] is '(':
                suffix=line[1:]

                # if suffix does not even look like a pathname, let's not bother walking it
                if suffix[0] not in './':
                    suffix=""

                # what we want is the longest prefix of suffix that _is_ a pathname
                while suffix and not os.path.isfile(suffix):
                    suffix=suffix[:-1]

                self.opened_files.append(suffix)

            line = line[1:]

    def get_current_file(self):
        """Returns the filename where the tracker believes we are"""
        for i in range(-1, -len(self.opened_files)-1,-1):
            if self.opened_files[i]:
                return self.opened_files[i]
        # GS-2018-04-10-17:06 bugfix for test-case #48
        return "./"+jobname+".tex"

    def print(self,text):
        """Prints either `text', `file:line text', or text (page n), etc."""
        if self.print_all_filenames or (self.get_current_file() != "./"+jobname+".tex"):
            print("in file %s:"%self.get_current_file(), end=' ')
            self.print_all_filenames = True
        if self.current_pagenum > self.max_pagenum:
            # page number is obviously wrong => unhelpful => skip it
            print(text)
        else:
            print(text + " (page %d)" % self.current_pagenum)

#####################################################################
# Warning pretty-print

class WarningParser():
    def __init__(self,printer):
        # actual message to be printed on the console
        self.text = ''
        # in long warnings, we expect loglines to have a prefix e.g. '(hyperref)'
        self.prefix = ''
        # handle to the PageFileTracker
        self.printer=printer
        
    def parse(self,line):
        if (len(line) == 0) and (len(self.text)>0): # now is finally the time to spit out the message
            self.printer.print(self.text)
            self.text=''
            self.prefix=''
            
        elif self.prefix and line.startswith(self.prefix):  # we are in the middle of a (prefixed)-warning
            self.text += ' '+line[len(self.prefix):]

        elif re_warning.match(line): # Class and package warnings
            m   = re_warning.match(line)
            pkg = m.groupdict()["pkg"]
            self.prefix = ("(%s)" % pkg).ljust(m.start("text")) # guess the prefix. BUT: can be wrong, cf #52
            self.text=line

        elif line.startswith('LaTeX Warning: '): # cf #05, #09, #13, #17, #27...
            self.text=line
            if ' Unused global option(s):' in line:
                self.prefix="    " # offending options on next logline, cf #46

        elif line.startswith('pdfTeX warning:'): # cf #36, #48
            self.printer.print(line) # pdfTeX warnings are always single-line

        elif line.startswith(r'Overfull ') or line.startswith(r'Underfull '): # cf #30, #34
            if options.nobadboxes is False:
                self.printer.print(line) # bad boxes are always single-line

        elif len(self.text)>0: # we are in the middle of a non-prefixed warning e.g. #52
            self.text += ' '+line.strip()

def print_warnings():
    tracker=PageFileTracker()
    wp = WarningParser(tracker)
    acc=''
    for line in open( jobname+".log" ).read().splitlines():
        
        # TeX breaks outputs at 79 characters. here we rejoin the fragments
        if len(line)==79:
            acc+=line
            continue
        elif acc:
            line=acc+line
            acc=""

        tracker.update_page(line)
        tracker.update_currentfile(line) 

        wp.parse(line)

#####################################################################
# Main compilation stuff
            
def snapshot():
    """Take a 'snapshot' of known auxiliary files.
Returns a dictionary where keys are file names and values are file contents."""

    suffixes =  [".aux",".glo",".bbl",".blg"]
    snapshot=dict()
    for filename in [ jobname + suffix for suffix in suffixes]:
        if os.path.exists(filename):
           snapshot[filename]=open(filename,"rb").read()
        else:
            snapshot[filename]=None
    return snapshot

def changedfiles(oldsnapshot, newsnapshot):
    """Compare the two snapshots and return an iterator with all the filenames that differ"""
    for filename in newsnapshot:
        if filename not in oldsnapshot:
            yield filename
        elif oldsnapshot[filename] != newsnapshot[filename]:
            yield filename

# note: each of the functions we call here will raise an exception if
# something goes wrong -> no need for explicit error-checking
def latex_full_build():
    before=snapshot()
    print("compiling %s..." % (jobname+'.tex'))
    run_pdflatex() # if errors, will print them before raising exception
    after=snapshot()

    if bibtex_needed(before[jobname+".aux"],after[jobname+".aux"]):
        run_bibtex()
        after=snapshot() # bibtex may or may not require a recompilation (cf #45 #32)

    # We recompile the latex document stubbornly until all the
    # auxiliary files (ie .aux .log etc) reach a fixpoint.
    while before != after:
        for filename in changedfiles(before, after):
            # print "file changed:", filename
            if filename == jobname+".glo": # cf #38 and #39
                print("running makeglossaries on %s..." % jobname)
                subprocess.check_output(["makeglossaries",jobname])
            
        before=snapshot()
        print("recompiling %s..." % (jobname+'.tex'))
        run_pdflatex() 
        after=snapshot()
    
    print_warnings()

#####################################################################
# Conmmand-line Interface

jobname=None
if __name__ == '__main__':

    # option parsing
    argparser = argparse.ArgumentParser()
    argparser.add_argument('--version', help='print version information and exit',action="version",
                           version='%(prog)s 2019-10-31')
    argparser.add_argument('-l','--loop', help='loop-forever mode',action="store_true")
    argparser.add_argument('-b','--nobadboxes', help='ignore warnings about overfull and underfull boxes', action="store_true")
    argparser.add_argument('filename',metavar='FILENAME', help='your latex file')
    options=argparser.parse_args()

    # argument parsing
    jobname=options.filename
    if not os.path.exists(jobname+'.tex'): jobname=jobname.replace('.tex','')
    if not os.path.exists(jobname+'.tex'): 
        print(argparser.prog+": cannot find file '"+options.filename+"'")
        sys.exit(1)

    # run-once-only mode
    if not options.loop:
        try:
            latex_full_build()
        except (LatexCompileError,BibtexError):
            sys.exit(1)
        else:
            sys.exit(0)

    # run-forever mode
    try:
        latex_full_build()
    except (LatexCompileError,BibtexError):
        pass
    except KeyboardInterrupt:
        print()# newline after ^C to look good
        sys.exit(0)
    
    while True:

        try:
            time.sleep(1)
        except KeyboardInterrupt:
            print()# newline after ^C to look good
            sys.exit(0)

        last_compile_time=os.path.getmtime(jobname+".log")

        must_recompile=False
        for (dirpath,subdirs,filenames) in os.walk("."):
            for filename in filenames:
                filepath=dirpath+"/"+filename
                if not os.path.isfile(filepath): continue 
                if os.path.getmtime(filepath) > last_compile_time:
                    # print "recent file:", filepath
                    must_recompile=True
                    
        if not must_recompile:
            continue

        try:
            latex_full_build()
        except (LatexCompileError,BibtexError):
            # print 70*'='
            time.sleep(1)
        except KeyboardInterrupt:
            print()# newline after ^C to look good
            sys.exit(0)
